#dev deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-service
  namespace: development
  labels:
    app: a-service
spec:
  selector:
    matchLabels:
      app: a-service
  template:
    metadata:
      labels:
        app: a-service
    spec:
      containers:
        - name: a-service
          image: docker.io/a-service:dev-01
          imagePullPolicy: Always
  strategy:
    type: Recreate
  resources:
    limits:
    memory: 600Mi
    cpu: 2
  requests:
    memory: 300Mi
    cpu: 1
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: a-service
  namespace: development
  labels:
    deploymentName: a-service
spec:
  scaleTargetRef:
  deploymentName: a-service
  pollingInterval: 2
  cooldownPeriod: 15
  maxReplicaCount: 2  